
services:
  - docker

jobs:
  include:
    - stage: test
      before_script:
        - docker pull node:12
        - docker pull golang:1.12.7-stretch
      script:
        - docker run --rm -e CI=true -v $(pwd)/client:/src node:12 /bin/sh -c "cd src; npm install; npm test"
        - docker run --rm -e GO111MODULE=on -v $(pwd)/server:/go/src/server/ golang:1.12.7-stretch /bin/sh -c "cd /go/src/server; go get; go test -v ./..."

    # TODO: workflow

    # - stage: deploy to staging
    #   script: skip
    #   deploy:
    #     - provider: elasticbeanstalk
    #         zipfile: server
    #         skip_cleanup: true
    #         on:
    #           branch: master
    #     - provider: elasticbeanstalk
    #         zipfile: client
    #         skip_cleanup: true
    #         on:
    #           branch: master

    # - stage: deploy to production
    #   script: skip
    #   deploy:
    #     - provider: elasticbeanstalk
    #         zipfile: server
    #         skip_cleanup: true
    #         on:
    #           tags: true
    #           branch: master
    #     - provider: elasticbeanstalk
    #         zipfile: client
    #         skip_cleanup: true
    #         on:
    #           tags: true
    #           branch: master
    #     - provider: releases
    #         skip_cleanup: true
    #         on:
    #           tags: true
    #           branch: master
