
language: minimal

services:
  - docker

stages:
  - "tests"
  - name: "deploy to staging"
    if: branch = master
  # - deploy to production 
  #   if: branch = master AND tag IS present

jobs:
  include:
    - stage: "tests"
      name: "front end tests"
      script:
        - docker pull node:12
        - docker run --rm -e CI=true -v $(pwd)/client:/src node:12 /bin/sh -c "cd src; npm install; npm test"
    - script:
        - docker pull golang:1.12.7-stretch
        - docker run --rm -e GO111MODULE=on -v $(pwd)/server:/go/src/server/ golang:1.12.7-stretch /bin/sh -c "cd /go/src/server; go get; go test -v ./..."
        - zip -r server.zip server
      name: "back end tests"

    - stage: "deploy to staging"
      script:
        - cd client
        - zip -r client.zip .
      deploy:
        - provider: elasticbeanstalk
          access_key_id:
            secure: $AWS_ACCESS_KEY_ID
          secret_access_key:
            secure: $AWS_SECRET_ACCESS_KEY
          region: "us-east-1"
          app: "flowthru-staging"
          env: "staging-client"
          bucket_name: $AWS_BUCKET_NAME
          zip_file: "client.zip"
          skip_cleanup: true

    # - stage: deploy to production
    #   script: skip
    #   deploy:
    #     - provider: elasticbeanstalk
    #         zipfile: server
    #         skip_cleanup: true
    #     - provider: elasticbeanstalk
    #         zipfile: client
    #         skip_cleanup: true
    #     - provider: releases
    #         skip_cleanup: true

