
version: '3'

services:
  nodejs:
    image: flowapp/flow-node
    container_name: nodejs
    volumes: 
      - ${PWD}/.env:/usr/src/app/
    restart: unless-stopped
    command: npm run deploy
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: "postgres:11-alpine"
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app-network

  webserver:
    image: nginx:1.15-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "${NGINX_LOCAL_PORT1}:${NGINX_CONTAINER_PORT1}"
      - "${NGINX_LOCAL_PORT2}:${NGINX_CONTAINER_PORT2}"
    volumes:
      - web-root:${WEB_ROOT}
      - ${NGINX_LOCAL_CONF}:${NGINX_CONTAINER_CONF}
      - certbot-etc:${CERTBOT_ETC}
      - certbot-var:${CERTBOT_VAR}
      - dhparam:${DHPARAM_PATH}
    depends_on:
      - nodejs
      - postgres
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:${CERTBOT_ETC}
      - certbot-var:${CERTBOT_VAR}
      - web-root:${WEB_ROOT}
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=${WEB_ROOT} --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN1}  -d ${DOMAIN2}

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: ${WEB_ROOT_DRIVER}
    driver_opts:
      type: ${WEB_ROOT_DRIVER_OPTS_TYPE}
      device: ${WEB_ROOT_DRIVER_OPTS_DEVICE_PATH}
      o: ${WEB_ROOT_DRIVER_OPTS_O}
  dhparam:
    driver: ${DHPARAM_DRIVER}
    driver_opts:
      type: ${DHPARAM_DRIVER_OPTS_TYPE}
      device: ${DHPARAM_DRIVER_OPTS_DEVICE}
      o: ${DHPARAM_DRIVER_OPTS_O}

networks:
  app-network:
    driver: ${APP_NETWORK_DRIVER}
