name: Go

on:
  push:
    branches: [ master ]
#    paths:
#    - 'server/**'
  pull_request:
    branches: [ master ]
#    paths:
#    - 'server/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      env:
        GO111MODULE: on
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build database
      working-directory: ./database
      run: |
        docker build . -t flowthru-db
        docker run -d --name flowthru-db -p 127.0.0.1:80:5432 flowthru-db
        sleep 15
        docker logs flowthru-db

    - name: Install dependencies
      working-directory: ./server
      run: go get -v -t -d ./...

    - name: Test
      env:
        FLOWTHRU_TEST_DB_HOST: localhost
        FLOWTHRU_TEST_DB_PORT: 80
        FLOWTHRU_TEST_DB_USER: user
        FLOWTHRU_TEST_DB_PASSWORD: password
        FLOWTHRU_TEST_DB_NAME: test
      working-directory: ./server
      run: go test -v ./...
