name: Go

on:
  push:
    branches: [ master ]
    paths:
    - 'cmd/**'
    - 'internal/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'cmd/**'
    - 'internal/**'

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build database
      working-directory: ./internal/repository/pg
      run: |
        docker build . -t flowthru-db
        docker run -d --name flowthru-db -p 127.0.0.1:5432:5432 flowthru-db
        sleep 15
        docker logs flowthru-db
        docker container ls -a

    - name: Install dependencies
      run: go get -v -t -d ./...

    - name: Build
      working-directory: ./cmd
      run: go build -o flowthru.out

    - name: Run Tests
      run: go test -v ./...