name: Node.js

on:
  push:
    branches: [ master ]
    paths:
    - 'web-app/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'web-app/**'

jobs:
  test:
    name: Node.js Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies 
      working-directory: ./web-app
      run: yarn install

    - name: Build
      working-directory: ./web-app
      run: yarn build .
      env:
        CI: true

    - name: Run Tests 
      working-directory: ./web-app
      run: yarn test
      env:
        CI: true

